---
title: "Untitled"
author: "Yujia_Wang"
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pesticides <- read_csv("Pesticides(1).csv")
strawb <- read.csv("Strawberries.csv")

# deal with strawb
drop_no_info_cols <- function(df){
  cnames = colnames(strawb)
  T = NULL
  for(i in 1:ncol(df)){T <- c(T, nrow(unique(df[i])))}
  drop_cols <- cnames[which(T == 1)]
  return(select(df, !all_of(drop_cols)))
}
strawb <- drop_no_info_cols(strawb)
strawb %<>% separate(col=Data.Item,
                     into = c("Strawberries", "items", "discription", "units"),
                     sep = ",",
                     fill = "right")
strawb %<>%  separate(col=Domain,
                      into = c("dname", "type" ), 
                      sep = ",", 
                      fill = "right")
strawb %<>% 
  mutate(Chemicals = Domain.Category) %>% 
  relocate(Chemicals, .after = Domain.Category) 
bb <- strawb$Chemicals %>% str_detect("CHEM")
ind_C <- (!bb)*(1:dim(strawb)[1])
r1 <- ind_C[ind_C > 0]
strawb$Chemicals[r1] <- " "
strawb %<>% separate(col = Chemicals,
                     into = c("title", "details"),
                     sep = '[:]',
                     fill = "right",)
strawb %<>% mutate(details = str_extract(str_trim(details) ,"[^(].*[^)]") )
strawb %<>% mutate(type = str_trim(type))

# deal with strawb_select
strawb_select <- select(strawb, Year, State, items, discription, units, dname, type, details, Value)
strawb_select <- strawb_select %>% 
  filter(!is.na(details))
strawb_select %<>% separate(col = details, 
                            into = c("chemical_name", "chemical_id"), 
                            sep = "=", 
                            fill = "right")
strawb_select <- strawb_select %>% 
  mutate(chemical_name = str_trim(chemical_name))

# deal with pesticides1
pesticides <- pesticides %>% 
  filter(!is.na(Pesticide))
pesticides <- pesticides %>% 
  mutate(Pesticide = toupper(Pesticide))
pesticides1 <- pesticides %>% 
  rename(chemical_name = Pesticide)

# deal with joined2
# install.packages("prob")
joined2 <- left_join(strawb_select, pesticides1,
                     by = "chemical_name")

# subset by state
california <- joined2 %>% 
  filter(State == "CALIFORNIA")
florida <- joined2 %>% 
  filter(State == "FLORIDA")
oregon <- joined2 %>% 
  filter(State == "OREGON")
washington <- joined2 %>% 
  filter(State == "WASHINGTON")

# subset by chemical type
cali_chem <- california %>% filter((type=="FUNGICIDE")|
                                   (type=="HERBICIDE")|
                                   (type=="INSECTICIDE"))
cali_other <- california %>% filter(type=="OTHER")

# subset by no chemical
cali_na <- california %>% filter(is.na(type)==TRUE)

# chemical data are classified according to year,unit of measurement,chemical type
cali_chem1 <- cali_chem %>% 
  group_by(Year, type, discription) %>% 
  summarise(count = n())

# value as.numeric
cali_chem$Value <- as.numeric(cali_chem$Value)

# sum
cali_chem1 <- cali_chem %>% 
  group_by(Year, type, discription) %>% 
  summarise(count = n(), value_sum = sum(Value))

# measured in lb larger than other units of measurement
aa <- !is.na(cali_chem$`Bee Toxins`)
ind_C1 <- (!aa)*(1:dim(cali_chem)[1])
r2 <- ind_C1[ind_C1>0]
cali_chem$`Bee Toxins`[r2] <- "none"

cali_chem_summary <- cali_chem %>% 
  group_by(Year,`Bee Toxins`) %>% 
  summarise(total_usage = sum(Value, na.rm = T))

# change position of slight,none
yy <- factor(as.factor(cali_chem_summary$`Bee Toxins`), levels = c("none", "slight" , "moderate", "high"))

cali_chem_summary$`Bee Toxins` <- yy

cali_chem_summary_ordered <- cali_chem_summary %>% 
  arrange(Year,`Bee Toxins`)

# total usage every year
cali_chem_summary1 <- cali_chem_summary %>% 
  group_by(Year) %>% 
  summarise(useageofyear = sum(total_usage))

# Bee toxicity of high, medium and low without use, percentage
perc_col = matrix(cbind(cali_chem_summary_ordered$total_usage[1:4] / 6046.092 , cali_chem_summary_ordered$total_usage[5:8] / 9177.122, cali_chem_summary_ordered$total_usage[9:12] / 8457.764), nrow = 12)

cali_chem_summary_ordered$percentage <- perc_col

#bar plot
ggplot(cali_chem_summary_ordered, aes(x = Year, y = percentage, fill = `Bee Toxins`)) +
  geom_col(position = "dodge")

#stacked plot
ggplot(cali_chem_summary_ordered, aes(fill = `Bee Toxins`, y = percentage, x = Year)) + 
  geom_bar(position="stack", stat="identity")
```











