---
title: "Final"
author: "Yujia_Wang"
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(dplyr)
library(leaflet)
library(usmap)
library(ggplot2)
```

Yujia
```{r}
library(tidyverse)
library(magrittr)
library(dplyr)

#############################################################

## Load data

strawb <- read.csv("Strawberries.csv")

#############################################################

## Drop the no-info columns

drop_no_info_cols <- function(df){
  cnames = colnames(strawb)
  T = NULL
  for(i in 1:ncol(df)){
    T <- c(T, nrow(unique(df[i])))
    }
  drop_cols <- cnames[which(T == 1)]
  return(select(df, !all_of(drop_cols)))
}

strawb <- drop_no_info_cols(strawb)

#############################################################

## Divide "Data.Item" into 4 groups

strawb %<>% separate(col=Data.Item,
                     into = c("Strawberries", "items", "discription", "units"),
                     sep = ",",
                     fill = "right")

## Data explore: see "Strawberries", "items", "discription", "units" information

distinct(strawb, Strawberries)
distinct(strawb, items)
distinct(strawb, discription)
distinct(strawb, units)

#############################################################

## Separate "Domain" into 2 columns

strawb %<>%  separate(col=Domain,
                      into = c("dname", "type" ), 
                      sep = ",", 
                      fill = "right")

## Data explore

distinct(strawb, dname)
distinct(strawb, type)

#############################################################

## Make a copy of "Domain.Category", called "Chemicals"

strawb %<>% 
  mutate(Chemicals = Domain.Category) %>% 
  relocate(Chemicals, .after = Domain.Category) 

## Vector of logicals for each row with "CHEM" at the start of strawb$Chemicals
## Select "CHEM" from Chemicals"

bb <- strawb$Chemicals %>% str_detect("CHEM")
sum(bb)

## Index 
# dim(x): http://www.stat.umn.edu/macanova/htmlhelp/node95.htm
# dim(x)[1] row, dim(x)[2] column

ind_C <- (!bb)*(1:dim(strawb)[1])

## Drop "0" from "ind_C"

r1 <- ind_C[ind_C > 0]

## Set entries in Chemicals column to " " if they don't start with "CHEM"

strawb$Chemicals[r1] <- " "

#############################################################

## Now we need a list of chemicals
## Divide "Chemicals" into 2 groups

strawb %<>% separate(col = Chemicals,
                     into = c("title", "details"),
                     sep = ":",
                     fill = "right")

# str_trim(): removes Spaces from the beginning and end of the string
# str_squish(): also reduces the duplicate Spaces in the string

strawb %<>% mutate(details = str_extract(str_trim(details) ,"[^(].*[^)]") )
strawb %<>% mutate(type = str_trim(type))

## Data explore

distinct(strawb, details)
distinct(strawb, type)

#############################################################

## Note that the 3021 rows in strawb have been spit into three subsets here
## But, be careful -- the columns are sill not sorted out

strawb_chem <- strawb %>% filter((type=="FUNGICIDE")|
                                   (type=="HERBICIDE")|
                                   (type=="INSECTICIDE"))

strawb_other <- strawb %>% filter(type=="OTHER")

strawb_na <- strawb %>% filter(is.na(type)==TRUE)

#############################################################

## look at herbicides in particular

strawb_herb <- strawb %>% filter(type=="HERBICIDE")

distinct(strawb_herb, details)

## more exploration

distinct(strawb_chem, details)
distinct(strawb_other, details)
distinct(strawb_na, details)

#############################################################

pesticides <- read_csv("Pesticides(1).csv")
pesticides

#Delete "N/A" from "Pesticide"

pesticides <- filter(pesticides, !is.na(Pesticide))

#Delete "N/A" from "details"

strawb_new <- filter(strawb, !is.na(details))

## Divide "details" into 2 groups

strawb_new %<>% separate(col = details, 
                            into = c("chemical_name", "chemical_id"), 
                            sep = "=", 
                            fill = "right")

#Capitalization of the "Pesticide" so that it matches the the dataset "strawb"

pesticides <- mutate(pesticides, Pesticide = toupper(Pesticide))

#trimws: Deletes leading/trailing Spaces

strawb_new <- mutate(strawb_new, chemical_name = trimws(chemical_name))

## join two dataframe

joined <- inner_join(strawb_new, pesticides, 
                     by = c("chemical_name" = "Pesticide"))

## data exploration

distinct(joined,type)
distinct(joined,discription)

## select column

joined_new<-select(joined,Year,State,discription,type,chemical_name,Value, Carcinogen,"Hormone Disruptor",Neurotoxins,"Developmental or Reproductive Toxins","Bee Toxins")

#############################################################

## data exploration of "State"

distinct(strawb_new, State)

## Divide by "Year"(only have 2019\2018\2016),explore every "Year" by "State"

joined_new_2019 <- joined_new[joined_new$Year == 2019, ] 
table(joined_new_2019$State)
joined_new_2018 <- joined_new[joined_new$Year == 2018, ] 
table(joined_new_2018$State)
joined_new_2016 <- joined_new[joined_new$Year == 2016, ] 
table(joined_new_2016$State)

## Divide by region in different "Year"

joined_new_2019_CALIFORNIA <- joined_new_2019[joined_new_2019$State=="CALIFORNIA",]
table(joined_new_2019_CALIFORNIA$"Bee Toxins")
joined_new_2019_FLORIDA <- joined_new_2019[joined_new_2019$State=="FLORIDA",]
table(joined_new_2019_FLORIDA$"Bee Toxins")

joined_new_2018_CALIFORNIA <- joined_new_2018[joined_new_2018$State=="CALIFORNIA",]
table(joined_new_2018_CALIFORNIA$"Bee Toxins")
joined_new_2018_FLORIDA <- joined_new_2018[joined_new_2018$State=="FLORIDA",]
table(joined_new_2018_FLORIDA$"Bee Toxins")

joined_new_2016_CALIFORNIA <- joined_new_2016[joined_new_2016$State=="CALIFORNIA",]
table(joined_new_2016_CALIFORNIA$"Bee Toxins")
joined_new_2016_FLORIDA <- joined_new_2016[joined_new_2016$State=="FLORIDA",]
table(joined_new_2016_FLORIDA$"Bee Toxins")
joined_new_2016_OREGON <- joined_new_2016[joined_new_2016$State=="OREGON",]
table(joined_new_2016_OREGON$"Bee Toxins")
joined_new_2016_WASHINGTON <- joined_new_2016[joined_new_2016$State=="WASHINGTON",]
table(joined_new_2016_WASHINGTON$"Bee Toxins")

## pie plot in 2019
freq<-c(30,15,35)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2019_CALIFORNIA",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))

freq<-c(20,10,25)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2019_FLORIDA",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))

## pie plot in 2018
freq<-c(30,15,35)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2018_CALIFORNIA",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))

freq<-c(15,10,15)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2018_FLORIDA",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))

## pie plot in 2016
freq<-c(30,15,35)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2016_CALIFORNIA",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))

freq<-c(15,15,25)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2016_FLORIDA",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))

freq<-c(10,0,10)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2016_OREGON",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))

freq<-c(10,5,15)
piepercent<- paste(round(100*freq/sum(freq), 2), "%")
pie1=pie(freq,labels = piepercent,main="2016_WASHINGTON",col = rainbow(length(freq)),edges = 200, radius = 1)
legend("bottomright",legend=c("high","moderate","slight"),cex=0.5,fill=rainbow(length(freq)))
       
## map plot

library(leaflet)
a<- leaflet() %>%
  addTiles() %>%
  addMarkers(lng=-118.8, lat=36.7, popup="CALIFORNIA") %>%
  addMarkers(lng=-81.5, lat=27.8, popup="FLORIDA") %>%
  addMarkers(lng=-120.7, lat=44.0, popup="OREGON") %>%
  addMarkers(lng=-120.2, lat=47.3, popup="WASHINGTON")
a

library(usmap)
library(ggplot2)
state<-c("CALIFORNIA","FLORIDA","OREGON","WASHINGTON")
observation<-c(48,30,4,6)
dataframe <- data.frame(state,observation)
b<-plot_usmap(data = dataframe, values = "observation", color = "red") + 
  scale_fill_continuous(name = "observation", label = scales::comma) + 
  theme(legend.position = "right")
b
```

Jack
```{r}
##  for data info see
##  https://quickstats.nass.usda.gov/

##  Note: CV Coefficient of variation. Available for the 2012 Census of Agriculture
##        only. County-level CVs are generalized.

library(tidyverse)
library(magrittr)

## load data

strawb <- read.csv("Strawberries.csv")

##################################################
## Drop the no-info columns
##################################




drop_no_info_cols <- function(df){
  cnames = colnames(strawb)
  T = NULL
  for(i in 1:ncol(df)){T <- c(T, nrow(unique(df[i])))}
  drop_cols <- cnames[which(T == 1)]
  return(select(df, !all_of(drop_cols)))
}



strawb <- drop_no_info_cols(strawb)



#############################################################


strawb %<>% separate(col=Data.Item,
                into = c("Strawberries", "items", "discription", "units"),
                sep = ",",
                fill = "right")

####  explore

distinct(strawb, Strawberries)

distinct(strawb, items)

distinct(strawb, discription)

distinct(strawb, units)
  

################################################

## Separte Domain into 2 columns

strawb %<>%  separate(col=Domain,
                      into = c("dname", "type" ), 
                      sep = ",", 
                      fill = "right")
distinct(strawb, dname)


distinct(strawb, type)


###################################
## make a copy of Domain.Categoy

strawb %<>% 
  mutate(Chemicals = Domain.Category) %>% 
  relocate(Chemicals, .after = Domain.Category) 


## vector of logicals for each row with "CHEM" at 
## the start of strawb$Chemicals

bb <- strawb$Chemicals %>% str_detect("CHEM")

sum(bb)

## index 
ind_C <- (!bb)*(1:dim(strawb)[1])

## 
r1 <- ind_C[ind_C > 0]

## set entries in Chemicals column to " " if they don't start with CHEM

strawb$Chemicals[r1] <- " "

#########################################

## now we need a list of chemicals

strawb %<>% separate(col = Chemicals,
                               into = c("title", "details"),
                               sep = ":",
                               fill = "right")

strawb %<>% mutate(details = str_extract(str_trim(details) ,"[^(].*[^)]") )

strawb %<>% mutate(type = str_trim(type))


distinct(strawb, details)

distinct(strawb, type)

#################################################################
## Note that the 3021 rows in strawb have been spit into 
## three subsets here

## But, be careful -- the columns are sill not sorted out

strawb_chem <- strawb %>% filter((type=="FUNGICIDE")|
                                   (type=="HERBICIDE")|
                                   (type=="INSECTICIDE"))



strawb_other <- strawb %>% filter(type=="OTHER")


strawb_na <- strawb %>% filter(is.na(type)==TRUE)

##################################################################
## look at herbicides in particular

strawb_herb <- strawb %>% filter(type=="HERBICIDE")

distinct(strawb_herb, details)

##################################################################
## more exploration


distinct(strawb_chem, details)

distinct(strawb_other, details)

distinct(strawb_na, details)

#########################################################################
### explord California

strawb_chem <- drop_no_info_cols(strawb_chem)
strawb_other <- drop_no_info_cols(strawb_other)



chem_list <- distinct(strawb_chem, details)

chem_list <- rbind2(chem_list,distinct(strawb_other, details))

# 
# 
# strawb_california_2020 <- strawb %>% filter((State == "CALIFORNIA")&(Year==2020))
# 
# 
# ##  aa <- strawb$Year[4]
# ## GLUFOSINATE-AMMONIUM = 128850
# 
# 
# 
# strawb__2019_Californi_GLUFOSINATE_AMMONIUM <- strawb_herb %>% filter((State=="CALIFORNIA")&
#                                                                         (Year==2019)&
#                                                                         (details=="GLUFOSINATE-AMMONIUM = 128850"))
# 
# ### this table is full of repetition and multiple related measurements!!
# 
# ################################################################
# 
# ### let's look at the other states
# 
# 
# distinct(strawb_chem, State)
# 
# ######################################################################################
# ### focus on Florida
# 
# strawb_chem_FLORIDA_2020 <- strawb_chem %>% filter((State == "FLORIDA")&(Year==2020))
# 
# View(strawb_chem_FLORIDA_2020)
# 
# ## there's nothing in strawb_chem_FLORIDA_2020 -- California was the same way
# ## probably drop year 2020
# 
# strawb_chem_FLORIDA_2019 <- strawb_chem %>% filter((State == "FLORIDA")&(Year==2019))
# 
# View(strawb_chem_FLORIDA_2019)
# 
# 
# 
# 
# 
# strawb_herb_FLORIDA_2019  <- strawb_herb %>% filter((State == "FLORIDA")&(Year==2019))
# 
# View(strawb_herb_FLORIDA_2019)
# 
# ## get rid of as much redundant data as possible
# 
# 
# strawb_herb_FLORIDA_2019 <- drop_no_info_cols(strawb_herb_FLORIDA_2019)
# 
# View(strawb_herb_FLORIDA_2019)
# 
# 
# ## this is a table for Florida Strawberries Herbicides 2019
# ## get rid of the redundant Domain.Category column
# 
# strawb_herb_FLORIDA_2019 %<>% select(-Domain.Category)
# 
# 
# 
# View(strawb_herb_FLORIDA_2019)
# 
# 
# strawb_herb_FLORIDA_2019_a <- straw_h %>% pivot_wider()
# 
# 
# ###  Note that there is still a lot of clean-up left to do -- 
# ##   which could have been done earlier in the larger table
# ##   but we'll do it here 
# ##   also note that there is no data available -- except for the identity
# ##   of the herbicides used
# 
# 
# strawb_herb_FLORIDA_2019 %<>% separate(col = items,
#                                       into = c("it", "what"), 
#                                       sep = "-",
#                                       fill = "right")
# 
# ### drop column it
# 
# strawb_herb_FLORIDA_2019 %<>% select(-it)
# 
# ## relocate details to the first column
# 
# strawb_herb_FLORIDA_2019 %<>%  relocate(details, .before = what)
# 
# View(strawb_herb_FLORIDA_2019)
# 
# ## rename "details column to "herbicides"
# strawb_herb_FLORIDA_2019 %<>% rename(herbicides = details)


## Now you can clearly see that this is a small table of 5 herbicides measured in 5 ways

## use pivot to make your table wider.  


## This R script has taken you down a path from the large table about strawberries
## to this table about herbicide application in Florida.
## 
## Now, you're ready to go back to the start and deliver your exploration of the entire dataset.
## You can get tables for insecticides, herbicides, fungicides, and fertilizers for each state.
## 
## You don't know the toxicity for each chemical, but you have some examples of both dangerous
## chemicals and benign chemicals.  
## 
## you also don't have CV.  the NASS system has indicated the CV is only available 
## for the year 2021,  
##
## 
## 

pesticides <- read_csv("Pesticides(1).csv")
pesticides

strawb_select <- select(strawb, Year, State, items, discription, units, dname, type, details, Value)

strawb_select

pesticides <- filter(pesticides, !is.na(Pesticide))
strawb_select <- filter(strawb_select, !is.na(details))

strawb_select %<>% separate(col = details, into = c("chemical_name", "chemical_id"), sep = "=", fill = "right")

pesticides <- mutate(pesticides, Pesticide = toupper(Pesticide))
strawb_select <- mutate(strawb_select, chemical_name = trimws(chemical_name))

joined <- inner_join(strawb_select, pesticides, by = c("chemical_name" = "Pesticide"))
#Question: Explore relationship between use of chemical 
#  (effectiveness?) and amount of bee toxin it has. Stratify by state
#  to find relationship, 

names(joined)<-make.names(names(joined),unique = TRUE)
joined$Value <- as.numeric(gsub(",", "",joined$Value))

groups <- unique(joined$discription)
for (group in groups){
  df <- filter(joined, discription == group)
  print(ggplot(data = df) + 
    geom_jitter(mapping = aes(x = Bee.Toxins, y=Value, color = Bee.Toxins), size = 3)+
      ggtitle(group))
}

states <- unique(joined$State)
for (state in states){
  df <- filter(joined, State == state, discription == " MEASURED IN PCT OF AREA BEARING")
  print(ggplot(data = df) + 
          geom_jitter(mapping = aes(x = Bee.Toxins, y=Value, color = Bee.Toxins), size = 3)+
          ggtitle(state))
}
```

Xiang
```{r}

```

Danny
```{r}
##  for data info see
##  https://quickstats.nass.usda.gov/

##  Note: CV Coefficient of variation. Available for the 2012 Census of Agriculture
##        only. County-level CVs are generalized.

library(tidyverse)
library(magrittr)

#############################################################
## load data

strawb <- read.csv("Strawberries.csv")

#############################################################
## Drop the no-info columns

#去掉没有信息的列

drop_no_info_cols <- function(df){
  cnames = colnames(strawb)
  T = NULL
  for(i in 1:ncol(df)){T <- c(T, nrow(unique(df[i])))}
  drop_cols <- cnames[which(T == 1)]
  return(select(df, !all_of(drop_cols)))
}

strawb <- drop_no_info_cols(strawb)

#############################################################

#把"Data.Item"分成4个部分

strawb %<>% separate(col=Data.Item,
                     into = c("Strawberries", "items", "discription", "units"),
                     sep = ",",
                     fill = "right")

## explore

#看看straw里的"Strawberries", "items", "discription", "units"这几列有哪些类信息

distinct(strawb, Strawberries)
distinct(strawb, items)
distinct(strawb, discription)
distinct(strawb, units)
?distinct



#############################################################
## Separate Domain into 2 columns

#把"Domain"分成2个部分

strawb %<>%  separate(col=Domain,
                      into = c("dname", "type" ), 
                      sep = ",", 
                      fill = "right")

distinct(strawb, dname)
distinct(strawb, type)

#############################################################
## make a copy of Domain.Category

#创建"Chemicals",内容等于"Domain.Category"

strawb %<>% 
  mutate(Chemicals = Domain.Category) %>% 
  relocate(Chemicals, .after = Domain.Category) 

## vector of logicals for each row with "CHEM" at 
## the start of strawb$Chemicals

#把"Chemicals"里写了"CHEM"的挑出来,然后看有多少个

bb <- strawb$Chemicals %>% str_detect("CHEM")
bb
sum(bb)
?str_detect


## index 

#dim(x)讲解：http://www.stat.umn.edu/macanova/htmlhelp/node95.htm
#dim(x)[1]是行数，dim(x)[2]是列数

ind_C <- (!bb)*(1:dim(strawb)[1])

#去掉ind_C中的0
#r1即为chemical 列中不含字符串“CHEM”的项的index
r1 <- ind_C[ind_C > 0]
## set entries in Chemicals column to " " if they don't start with CHEM

#将"Chemicals"里没有写"CHEM"的项变成空的

strawb$Chemicals[r1] <- " "

strawb$Chemicals[r1]

#############################################################
## now we need a list of chemicals

#把"Chemicals"分成2个部分

# This line of code change the setting, helping us skip any entry that cannot be translated.
# https://stackoverflow.com/questions/4993837/r-invalid-multibyte-string
Sys.setlocale("LC_ALL", "C")


strawb %<>% separate(col = Chemicals,
                     into = c("title", "details"),
                     sep = '[:]',
                     fill = "right",)






#str_trim()从字符串的开头和结尾删除空格
#str_squish()还减少了字符串内的重复空格
library(stringr)
?str_extract()

# ----------------------------------
distinct(strawb, details)
unique(str_trim(strawb$details))
unique(strawb$details)
unique(str_extract(str_trim(strawb$details) ,"[^(].*[^)]")) 
#其中[^(]意思是以(开头的 .的意思不明 *意思是重复此操作多次 [^)]意思是匹配)
# 见10:03   https://www.youtube.com/watch?v=PcUJXrN-C_E&ab_channel=RProgramming

unique(str_extract(str_trim(strawb$details) ,"[^(].+[^)]"))
# 这种方式也可取出括号中的内容
# https://stackoverflow.com/questions/38231081/extract-info-inside-parenthesis-in-r
unique(str_match(str_trim(strawb$details), "\\((.*)\\)"))

# -----------------------------------

# 取出detail列的括号中的内容(除去括号)，原理见上
strawb %<>% mutate(details = str_extract(str_trim(details) ,"[^(].*[^)]") )
# 除掉type列的空格
strawb %<>% mutate(type = str_trim(type))


distinct(strawb, details)
distinct(strawb, type)


#############################################################
## Note that the 3021 rows in strawb have been spit into three subsets here
## But, be careful -- the columns are sill not sorted out
## 根据化学类型（type列）把数据分成了四个类别
strawb_chem <- strawb %>% filter((type=="FUNGICIDE")|
                                   (type=="HERBICIDE")|
                                   (type=="INSECTICIDE"))

strawb_other <- strawb %>% filter(type=="OTHER")

strawb_na <- strawb %>% filter(is.na(type)==TRUE)

#############################################################
## look at herbicides in particular

strawb_herb <- strawb %>% 
  filter(type=="HERBICIDE")

distinct(strawb_herb, details)

## more exploration

distinct(strawb_chem, details)
distinct(strawb_other, details)
distinct(strawb_na, details)

#############################################################
#############################################################
## explore California

strawb_chem <- drop_no_info_cols(strawb_chem)
strawb_other <- drop_no_info_cols(strawb_other)
names(strawb_chem)
names(strawb)

chem_list <- distinct(strawb_chem, details)

chem_list <- rbind2(chem_list,distinct(strawb_other, details))

strawb_california_2020 <- strawb %>% filter((State == "CALIFORNIA")&(Year==2020))

## aa <- strawb$Year[4]
## GLUFOSINATE-AMMONIUM = 128850

strawb__2019_Californi_GLUFOSINATE_AMMONIUM <- strawb_herb %>% filter((State=="CALIFORNIA")&
                                                                        (Year==2019)&
                                                                        (details=="GLUFOSINATE-AMMONIUM = 128850"))

## this table is full of repetition and multiple related measurements!!

#############################################################
### let's look at the other states

distinct(strawb_chem, State)

#############################################################
#############################################################
### focus on Florida

strawb_chem_FLORIDA_2020 <- strawb_chem %>% 
  filter((State == "FLORIDA")&(Year==2020))


head(strawb_chem_FLORIDA_2020)

## there's nothing in strawb_chem_FLORIDA_2020 -- California was the same way
## probably drop year 2020

strawb_chem_FLORIDA_2019 <- strawb_chem %>% 
  filter((State == "FLORIDA")&(Year==2019))

head(strawb_chem_FLORIDA_2019)

strawb_herb_FLORIDA_2019  <- strawb_herb %>% 
  filter((State == "FLORIDA")&(Year==2019))

head(strawb_herb_FLORIDA_2019)
## get rid of as much redundant data as possible

strawb_herb_FLORIDA_2019 <- drop_no_info_cols(strawb_herb_FLORIDA_2019)
head(strawb_herb_FLORIDA_2019)
str(strawb_herb_FLORIDA_2019)


## this is a table for Florida Strawberries Herbicides 2019
## get rid of the redundant Domain.Category column

strawb_herb_FLORIDA_2019 %<>% 
  select(-Domain.Category)




head(strawb_herb_FLORIDA_2019)

# strawb_herb_FLORIDA_2019_a <- straw_h %>% 
#   pivot_wider()

## Note that there is still a lot of clean-up left to do -- 
## which could have been done earlier in the larger table
## but we'll do it here 
## also note that there is no data available -- except for the identity
## of the herbicides used

strawb_herb_FLORIDA_2019 %<>% separate(col = items,
                                       into = c("it", "what"), 
                                       sep = "-",
                                       fill = "right")


## drop column it

strawb_herb_FLORIDA_2019 %<>%
  select(-it)

## relocate details to the first column

strawb_herb_FLORIDA_2019 %<>%  
  relocate(details, .before = what)

head(strawb_herb_FLORIDA_2019)

## rename "details column to "herbicides"
strawb_herb_FLORIDA_2019 %<>% 
  rename(herbicides = details)

## Now you can clearly see that this is a small table of 5 herbicides measured in 5 ways
## use pivot to make your table wider.  

## This R script has taken you down a path from the large table about strawberries
## to this table about herbicide application in Florida.

## Now, you're ready to go back to the start and deliver your exploration of the entire dataset.
## You can get tables for insecticides, herbicides, fungicides, and fertilizers for each state.

## You don't know the toxicity for each chemical, but you have some examples of both dangerous
## chemicals and benign chemicals.  

## you also don't have CV.  the NASS system has indicated the CV is only available 
## for the year 2021,  

#############################################################
#############################################################
pesticides <- read_csv("Pesticides(1).csv")
pesticides

strawb_select <- select(strawb, Year, State, items, discription, units, dname, type, details, Value)
strawb_select
names(strawb_select)
head(strawb_select)

#去除"Pesticide"和"details"的NA项
pesticides <- pesticides %>% 
  filter(!is.na(Pesticide))
 
strawb_select <- strawb_select %>% 
  filter(!is.na(details))


strawb_select %<>% separate(col = details, 
                            into = c("chemical_name", "chemical_id"), 
                            sep = "=", 
                            fill = "right")
head(strawb_select)


#使"Pesticide"变成大写，这样可以match数据集strawb里的大写


pesticides <- pesticides %>% 
  mutate(Pesticide = toupper(Pesticide))

head(pesticides$Pesticide)

#trimws：删除前导/尾随空格
strawb_select <- strawb_select %>% 
  mutate(chemical_name = str_trim(chemical_name))

# view(strawb_select$chemical_name)

# strawb_select <- mutate(strawb_select, chemical_name = trimws(chemical_name))

# distinct(strawb_select, chemical_name)
# view(distinct(pesticides, Pesticide))


#-----------------------------------------------------------------
#joined <- inner_join(strawb_select, pesticides, 
#                     by = c("chemical_name" = "Pesticide"))

#--------------------------------------------------------------------


pesticides1 <- pesticides %>% 
  rename(chemical_name = Pesticide)
install.packages("prob")
# library(prob)
## Since inner_join drops all observations that do not match, I choose left_join here.
joined2 <- left_join(strawb_select, pesticides1,
                     by = "chemical_name")

library(dplyr)
# detach("package:stats")
# detach("timeSeries")

length(intersect(pesticides1$chemical_name, strawb_select$chemical_name))
length(unique(pesticides1$chemical_name))
length(unique(strawb_select$chemical_name))

head(pesticides1)
names(pesticides1)




#############################################################

strawb <- read.csv("Strawberries.csv")
joined2
unique(joined2$discription)


# 有几个州，几种计量单位。
distinct(joined2,State)
distinct(joined2, discription)

#按周subset数据
california <- joined2 %>% 
  filter(State == "CALIFORNIA")
florida <- joined2 %>% 
  filter(State == "FLORIDA")
oregon <- joined2 %>% 
  filter(State == "OREGON")
washington <- joined2 %>% 
  filter(State == "WASHINGTON")

# 按化学物质种类subset 加州的数据

cali_chem <- california %>% filter((type=="FUNGICIDE")|
                                   (type=="HERBICIDE")|
                                   (type=="INSECTICIDE"))

cali_other <- california %>% filter(type=="OTHER")

#no chemical
cali_na <- california %>% filter(is.na(type)==TRUE)


#其中， 含化学物质的按照年份，化学物质种类 计量单位分类。

cali_chem1 <- cali_chem %>% 
  group_by(Year, type, discription) %>% 
  summarise(count = n())

# 我们发现1.加州2017和2020年数据缺失 2. 五种计量单位的使用频率差不多。

#讲value一栏转化为numeric
cali_chem$Value <- as.numeric(cali_chem$Value)

# 在分类总结中加入平均的value, 出现了错误。
cali_chem1 <- cali_chem %>% 
  group_by(Year, type, discription) %>% 
  summarise(count = n(), value_sum = sum(Value))


# 我们发现measured in lb明显大与其它计量单位的量。此处应查pdf关于计量单位的描述作出相应调整。



aa <- !is.na(cali_chem$`Bee Toxins`)
ind_C1 <- (!aa)*(1:dim(cali_chem)[1])
r2 <- ind_C1[ind_C1>0]
cali_chem$`Bee Toxins`[r2] <- "none"


cali_chem_summary <- cali_chem %>% 
  group_by(Year,`Bee Toxins`) %>% 
  summarise(total_usage = sum(Value, na.rm = T))



#尝试给slight 和 none换个顺序

yy <- factor(as.factor(cali_chem_summary$`Bee Toxins`), levels = c("none", "slight" , "moderate", "high"))

cali_chem_summary$`Bee Toxins` <- yy

cali_chem_summary_ordered <- cali_chem_summary %>% 
  arrange(Year,`Bee Toxins`)


# 算出每年总用量
cali_chem_summary1 <- cali_chem_summary %>% 
  group_by(Year) %>% 
  summarise(useageofyear = sum(total_usage))


#整理出每年的关于蜜蜂毒性的高中低无的使用量，百分比
perc_col = matrix(cbind(cali_chem_summary_ordered$total_usage[1:4] / 6046.092 , cali_chem_summary_ordered$total_usage[5:8] / 9177.122, cali_chem_summary_ordered$total_usage[9:12] / 8457.764), nrow = 12)
cali_chem_summary_ordered$percentage <- perc_col

# ggplot(cali_chem_summary) +
#  geom_histogram(aes(x = Year, y = percentage), stat = "identity", fill = Bee Toxins, width = 0.4)
 # geom_histogram(aes(x = ages, y = value), stat = "identity", fill = "blue", width = 0.5, position = "dodge")

ggplot(cali_chem_summary_ordered, aes(x = Year, y = percentage, fill = `Bee Toxins`)) +
  geom_col(position = "dodge")



#
#stacked plot
ggplot(cali_chem_summary_ordered, aes(fill = `Bee Toxins`, y = percentage, x = Year)) + 
  geom_bar(position="stack", stat="identity")

# About map. Shiny: scroller: year
#                color: f that maps percentage of useage in high level bee toxin chemicals in this state. use select input.
# make the stacked 
```




```




