---
title: "Untitled"
author: "Yujia_Wang"
date: "11/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
strawb_select <- select(strawb, Year, State, items, discription, units, dname, type, details, Value)

pesticides <- filter(pesticides, !is.na(Pesticide))
strawb_select <- filter(strawb_select, !is.na(details))

strawb_select %<>% separate(col = details, into = c("chemical_name", "chemical_id"), sep = "=", fill = "right")

pesticides <- mutate(pesticides, Pesticide = toupper(Pesticide))
strawb_select <- mutate(strawb_select, chemical_name = trimws(chemical_name))

joined <- inner_join(strawb_select, pesticides, by = c("chemical_name" = "Pesticide"))

#point plot

names(joined)<-make.names(names(joined),unique = TRUE)
joined$Value <- as.numeric(gsub(",", "",joined$Value))

groups <- unique(joined$discription)
for (group in groups){
  df <- filter(joined, discription == group)
  print(ggplot(data = df) + 
    geom_jitter(mapping = aes(x = Bee.Toxins, y=Value, color = Bee.Toxins), size = 3)+
      ggtitle(group))
}

states <- unique(joined$State)
for (state in states){
  df <- filter(joined, State == state, discription == " MEASURED IN PCT OF AREA BEARING")
  print(ggplot(data = df) + 
          geom_jitter(mapping = aes(x = Bee.Toxins, y=Value, color = Bee.Toxins), size = 3)+
          ggtitle(state))
}
```







